2025-03-16 16:20:05,622 INFO    MainThread:7716 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-16 16:20:05,622 INFO    MainThread:7716 [wandb_setup.py:_flush():67] Configure stats pid to 7716
2025-03-16 16:20:05,622 INFO    MainThread:7716 [wandb_setup.py:_flush():67] Loading settings from C:\Users\shrey\.config\wandb\settings
2025-03-16 16:20:05,622 INFO    MainThread:7716 [wandb_setup.py:_flush():67] Loading settings from C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\settings
2025-03-16 16:20:05,622 INFO    MainThread:7716 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-16 16:20:05,622 INFO    MainThread:7716 [wandb_init.py:setup_run_log_directory():647] Logging user logs to C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250316_162005-6rwqfpn9\logs\debug.log
2025-03-16 16:20:05,623 INFO    MainThread:7716 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250316_162005-6rwqfpn9\logs\debug-internal.log
2025-03-16 16:20:05,623 INFO    MainThread:7716 [wandb_init.py:init():761] calling init triggers
2025-03-16 16:20:05,623 INFO    MainThread:7716 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-16 16:20:05,623 INFO    MainThread:7716 [wandb_init.py:init():784] starting backend
2025-03-16 16:20:05,623 INFO    MainThread:7716 [wandb_init.py:init():788] sending inform_init request
2025-03-16 16:20:05,637 INFO    MainThread:7716 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-16 16:20:05,638 INFO    MainThread:7716 [wandb_init.py:init():803] backend started and connected
2025-03-16 16:20:05,641 INFO    MainThread:7716 [wandb_init.py:init():896] updated telemetry
2025-03-16 16:20:05,677 INFO    MainThread:7716 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-16 16:20:07,120 INFO    MainThread:7716 [wandb_init.py:init():995] starting run threads in backend
2025-03-16 16:20:07,435 INFO    MainThread:7716 [wandb_run.py:_console_start():2377] atexit reg
2025-03-16 16:20:07,436 INFO    MainThread:7716 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-16 16:20:07,436 INFO    MainThread:7716 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-16 16:20:07,436 INFO    MainThread:7716 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-16 16:20:07,439 INFO    MainThread:7716 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-16 16:53:33,652 WARNING MsgRouterThr:7716 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-16 16:53:33,655 INFO    MsgRouterThr:7716 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
