Traceback (most recent call last):
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_config.py", line 165, in __getattr__
    return self.__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_config.py", line 130, in __getitem__
    return self._items[key]
           ~~~~~~~~~~~^^^^^
KeyError: 'size_of_every_hidden_layer'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\main.py", line 208, in <module>
    main(args)
  File "C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\main.py", line 23, in main
    if not isinstance(wandb.config.size_of_every_hidden_layer, list):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_config.py", line 167, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'size_of_every_hidden_layer'
