2025-03-10 07:15:03,835 INFO    MainThread:17780 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 07:15:03,837 INFO    MainThread:17780 [wandb_setup.py:_flush():67] Configure stats pid to 17780
2025-03-10 07:15:03,837 INFO    MainThread:17780 [wandb_setup.py:_flush():67] Loading settings from C:\Users\shrey\.config\wandb\settings
2025-03-10 07:15:03,837 INFO    MainThread:17780 [wandb_setup.py:_flush():67] Loading settings from C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\settings
2025-03-10 07:15:03,837 INFO    MainThread:17780 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 07:15:03,839 INFO    MainThread:17780 [wandb_init.py:setup_run_log_directory():647] Logging user logs to C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250310_071503-3kwm0r2b\logs\debug.log
2025-03-10 07:15:03,841 INFO    MainThread:17780 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250310_071503-3kwm0r2b\logs\debug-internal.log
2025-03-10 07:15:03,841 INFO    MainThread:17780 [wandb_init.py:init():761] calling init triggers
2025-03-10 07:15:03,841 INFO    MainThread:17780 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'ReLU', 'batch_size': 32, 'beta': 0.016516348387805885, 'beta1': 0.981737063119684, 'beta2': 0.9984371357274968, 'epochs': 15, 'epsilon': 4.0686560534803586e-06, 'hidden_size': 128, 'learning_rate': 2.66434317038548e-05, 'loss': 'mean_squared_error', 'momentum': 0.9197213886261854, 'num_layers': 6, 'optimizer': 'nadam', 'weight_decay': 0.0001, 'weight_init': 'Xavier'}
config: {'_wandb': {}}
2025-03-10 07:15:03,841 INFO    MainThread:17780 [wandb_init.py:init():784] starting backend
2025-03-10 07:15:03,841 INFO    MainThread:17780 [wandb_init.py:init():788] sending inform_init request
2025-03-10 07:15:03,882 INFO    MainThread:17780 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-10 07:15:03,887 INFO    MainThread:17780 [wandb_init.py:init():803] backend started and connected
2025-03-10 07:15:03,889 INFO    MainThread:17780 [wandb_run.py:_config_callback():1261] config_cb None None {'activation': 'ReLU', 'batch_size': 32, 'beta': 0.016516348387805885, 'beta1': 0.981737063119684, 'beta2': 0.9984371357274968, 'epochs': 15, 'epsilon': 4.0686560534803586e-06, 'hidden_size': 128, 'learning_rate': 2.66434317038548e-05, 'loss': 'mean_squared_error', 'momentum': 0.9197213886261854, 'num_layers': 6, 'optimizer': 'nadam', 'weight_decay': 0.0001, 'weight_init': 'Xavier'}
2025-03-10 07:15:03,891 INFO    MainThread:17780 [wandb_init.py:init():896] updated telemetry
2025-03-10 07:15:04,023 INFO    MainThread:17780 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-10 07:15:04,781 INFO    MainThread:17780 [wandb_init.py:init():995] starting run threads in backend
2025-03-10 07:15:07,384 INFO    MainThread:17780 [wandb_run.py:_console_start():2377] atexit reg
2025-03-10 07:15:07,384 INFO    MainThread:17780 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-10 07:15:07,393 INFO    MainThread:17780 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-10 07:15:07,393 INFO    MainThread:17780 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-10 07:15:07,408 INFO    MainThread:17780 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-10 08:27:19,240 WARNING MsgRouterThr:17780 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-10 08:27:19,244 INFO    MsgRouterThr:17780 [mailbox.py:close():115] Closing mailbox, abandoning 0 handles.
