2025-03-09 14:23:14,463 INFO    MainThread:14696 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 14:23:14,463 INFO    MainThread:14696 [wandb_setup.py:_flush():67] Configure stats pid to 14696
2025-03-09 14:23:14,463 INFO    MainThread:14696 [wandb_setup.py:_flush():67] Loading settings from C:\Users\shrey\.config\wandb\settings
2025-03-09 14:23:14,463 INFO    MainThread:14696 [wandb_setup.py:_flush():67] Loading settings from C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\settings
2025-03-09 14:23:14,463 INFO    MainThread:14696 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 14:23:14,463 INFO    MainThread:14696 [wandb_init.py:setup_run_log_directory():647] Logging user logs to C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250309_142314-6xwdk5mh\logs\debug.log
2025-03-09 14:23:14,463 INFO    MainThread:14696 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250309_142314-6xwdk5mh\logs\debug-internal.log
2025-03-09 14:23:14,463 INFO    MainThread:14696 [wandb_init.py:init():761] calling init triggers
2025-03-09 14:23:14,463 INFO    MainThread:14696 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-09 14:23:14,463 INFO    MainThread:14696 [wandb_init.py:init():784] starting backend
2025-03-09 14:23:14,463 INFO    MainThread:14696 [wandb_init.py:init():788] sending inform_init request
2025-03-09 14:23:14,479 INFO    MainThread:14696 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-09 14:23:14,480 INFO    MainThread:14696 [wandb_init.py:init():803] backend started and connected
2025-03-09 14:23:14,481 INFO    MainThread:14696 [wandb_init.py:init():896] updated telemetry
2025-03-09 14:23:14,515 INFO    MainThread:14696 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-09 14:23:15,894 INFO    MainThread:14696 [wandb_init.py:init():995] starting run threads in backend
2025-03-09 14:23:16,120 INFO    MainThread:14696 [wandb_run.py:_console_start():2377] atexit reg
2025-03-09 14:23:16,120 INFO    MainThread:14696 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-09 14:23:16,121 INFO    MainThread:14696 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-09 14:23:16,121 INFO    MainThread:14696 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-09 14:23:16,123 INFO    MainThread:14696 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-09 14:23:22,395 WARNING MsgRouterThr:14696 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-09 14:23:22,397 INFO    MsgRouterThr:14696 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
