2025-03-10 02:18:09,876 INFO    MainThread:10760 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 02:18:09,876 INFO    MainThread:10760 [wandb_setup.py:_flush():67] Configure stats pid to 10760
2025-03-10 02:18:09,877 INFO    MainThread:10760 [wandb_setup.py:_flush():67] Loading settings from C:\Users\shrey\.config\wandb\settings
2025-03-10 02:18:09,877 INFO    MainThread:10760 [wandb_setup.py:_flush():67] Loading settings from C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\settings
2025-03-10 02:18:09,877 INFO    MainThread:10760 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 02:18:09,878 INFO    MainThread:10760 [wandb_init.py:setup_run_log_directory():647] Logging user logs to C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250310_021809-739jt6rg\logs\debug.log
2025-03-10 02:18:09,882 INFO    MainThread:10760 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250310_021809-739jt6rg\logs\debug-internal.log
2025-03-10 02:18:09,882 INFO    MainThread:10760 [wandb_init.py:init():761] calling init triggers
2025-03-10 02:18:09,882 INFO    MainThread:10760 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 16, 'beta': 0.04590969882717585, 'beta1': 0.9845692271110378, 'beta2': 0.9973992659577228, 'epochs': 15, 'epsilon': 5.1371295482763855e-06, 'hidden_size': 64, 'learning_rate': 8.498635233761515e-05, 'loss': 'mean_squared_error', 'momentum': 0.9007713351517156, 'num_layers': 6, 'optimizer': 'rmsprop', 'weight_decay': 0.0005, 'weight_init': 'Xavier'}
config: {'_wandb': {}}
2025-03-10 02:18:09,882 INFO    MainThread:10760 [wandb_init.py:init():784] starting backend
2025-03-10 02:18:09,883 INFO    MainThread:10760 [wandb_init.py:init():788] sending inform_init request
2025-03-10 02:18:09,958 INFO    MainThread:10760 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-10 02:18:09,965 INFO    MainThread:10760 [wandb_init.py:init():803] backend started and connected
2025-03-10 02:18:09,969 INFO    MainThread:10760 [wandb_run.py:_config_callback():1261] config_cb None None {'activation': 'tanh', 'batch_size': 16, 'beta': 0.04590969882717585, 'beta1': 0.9845692271110378, 'beta2': 0.9973992659577228, 'epochs': 15, 'epsilon': 5.1371295482763855e-06, 'hidden_size': 64, 'learning_rate': 8.498635233761515e-05, 'loss': 'mean_squared_error', 'momentum': 0.9007713351517156, 'num_layers': 6, 'optimizer': 'rmsprop', 'weight_decay': 0.0005, 'weight_init': 'Xavier'}
2025-03-10 02:18:09,972 INFO    MainThread:10760 [wandb_init.py:init():896] updated telemetry
2025-03-10 02:18:10,130 INFO    MainThread:10760 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-10 02:18:11,062 INFO    MainThread:10760 [wandb_init.py:init():995] starting run threads in backend
2025-03-10 02:18:14,336 INFO    MainThread:10760 [wandb_run.py:_console_start():2377] atexit reg
2025-03-10 02:18:14,338 INFO    MainThread:10760 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-10 02:18:14,353 INFO    MainThread:10760 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-10 02:18:14,353 INFO    MainThread:10760 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-10 02:18:14,383 INFO    MainThread:10760 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-10 02:51:19,547 WARNING MsgRouterThr:10760 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 258, in _read_packet_bytes
    data = self._sock.recv(self._bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 262, in _read_packet_bytes
    raise SockClientClosedError from e
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-10 02:51:19,622 INFO    MsgRouterThr:10760 [mailbox.py:close():115] Closing mailbox, abandoning 3 handles.
