2025-03-08 17:27:21,062 INFO    MainThread:6432 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-08 17:27:21,062 INFO    MainThread:6432 [wandb_setup.py:_flush():67] Configure stats pid to 6432
2025-03-08 17:27:21,062 INFO    MainThread:6432 [wandb_setup.py:_flush():67] Loading settings from C:\Users\shrey\.config\wandb\settings
2025-03-08 17:27:21,062 INFO    MainThread:6432 [wandb_setup.py:_flush():67] Loading settings from C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\settings
2025-03-08 17:27:21,062 INFO    MainThread:6432 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-08 17:27:21,062 INFO    MainThread:6432 [wandb_init.py:setup_run_log_directory():647] Logging user logs to C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250308_172721-l143effr\logs\debug.log
2025-03-08 17:27:21,062 INFO    MainThread:6432 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250308_172721-l143effr\logs\debug-internal.log
2025-03-08 17:27:21,062 INFO    MainThread:6432 [wandb_init.py:init():761] calling init triggers
2025-03-08 17:27:21,062 INFO    MainThread:6432 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 16, 'beta': 0.5, 'beta1': 0.9, 'beta2': 0.999, 'epochs': 5, 'epsilon': 1e-06, 'hidden_size': 10, 'learning_rate': 0.001, 'loss': 'cross_entropy', 'momentum': 0.5, 'num_layers': 3, 'optimizer': 'adam', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-08 17:27:21,062 INFO    MainThread:6432 [wandb_init.py:init():784] starting backend
2025-03-08 17:27:21,062 INFO    MainThread:6432 [wandb_init.py:init():788] sending inform_init request
2025-03-08 17:27:21,084 INFO    MainThread:6432 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-08 17:27:21,085 INFO    MainThread:6432 [wandb_init.py:init():803] backend started and connected
2025-03-08 17:27:21,085 INFO    MainThread:6432 [wandb_run.py:_config_callback():1261] config_cb None None {'activation': 'sigmoid', 'batch_size': 16, 'beta': 0.5, 'beta1': 0.9, 'beta2': 0.999, 'epochs': 5, 'epsilon': 1e-06, 'hidden_size': 10, 'learning_rate': 0.001, 'loss': 'cross_entropy', 'momentum': 0.5, 'num_layers': 3, 'optimizer': 'adam', 'weight_decay': 0.0005, 'weight_init': 'random'}
2025-03-08 17:27:21,086 INFO    MainThread:6432 [wandb_init.py:init():896] updated telemetry
2025-03-08 17:27:21,113 INFO    MainThread:6432 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-08 17:27:22,605 INFO    MainThread:6432 [wandb_init.py:init():995] starting run threads in backend
2025-03-08 17:27:22,913 INFO    MainThread:6432 [wandb_run.py:_console_start():2377] atexit reg
2025-03-08 17:27:22,914 INFO    MainThread:6432 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-08 17:27:22,915 INFO    MainThread:6432 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-08 17:27:22,915 INFO    MainThread:6432 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-08 17:27:22,916 INFO    MainThread:6432 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-08 17:27:40,953 WARNING MsgRouterThr:6432 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-08 17:27:40,956 INFO    MsgRouterThr:6432 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
